import groovy.transform.ToString
import groovy.transform.EqualsAndHashCode

@ToString
@EqualsAndHashCode
class Person {
	String name
	int age
}

public static void main(String[] args) {
	new Person()  // has hashCode and equals methods on it too now autogenerated by AST
}